version: "3.8"
services:
    frontend:
        build:
            context: ./frontend # Replace with the actual path to your frontend code
            dockerfile: Dockerfile # Replace with the actual Dockerfile name
        container_name: frontend
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        depends_on:
            - backend

    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot:rw

    backend:
        build:
            context: ./backend # Replace with the actual path to your backend code
            dockerfile: Dockerfile # Replace with the actual Dockerfile name
        container_name: backend
        env_file:
            - ./backend/payroll_system/.env
        environment:
            - DB_HOST=database
        depends_on:
            - database

    database:
        image: postgres:latest # Replace with the actual image name or tag
        container_name: database
        env_file:
            - .env.db
        volumes:
            - db_volume:/var/lib/postgresql/data

volumes:
    db_volume:
