version: "3.8"
services:
    frontend:
        build:
            context: ./frontend # Replace with the actual path to your frontend code
            dockerfile: Dockerfile # Replace with the actual Dockerfile name
        container_name: frontend
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
            - ./data/dhparam:/etc/ssl/certs
            - media_volume:/mediafiles
        depends_on:
            - backend

    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot:rw
        depends_on:
            - frontend
        command: certonly --webroot --webroot-path=/var/www/certbot --email kk.singh4999@gmail.com --agree-tos --no-eff-email -d pay-per.me  -d www.pay-per.me

    backend:
        build:
            context: ./backend # Replace with the actual path to your backend code
            dockerfile: Dockerfile # Replace with the actual Dockerfile name
        container_name: backend
        env_file:
            - ./backend/payroll_system/.env
        environment:
            - DB_HOST=database
        depends_on:
            - database
        volumes:
            - media_volume:/payroll-system/backend/payroll_system/mediafiles

    database:
        image: postgres:16 # Specify PostgreSQL version 16
        container_name: database
        env_file:
            - .env.db
        volumes:
            - db_volume:/var/lib/postgresql/data

    backup:
        image: postgres:16 # Use the same PostgreSQL version
        container_name: db_backup
        depends_on:
            - database
        volumes:
            - ./backup:/backup # Mount a volume to store backups
            - ../database_backups:/database_backups # Mount a volume to store backups

        env_file:
            - .env.db
        environment:
            - DB_HOST=database
        command: /bin/bash /backup/start_backup.sh

volumes:
    db_volume:
    media_volume:
    # Volume for storing backups
    # backup:
