# Generated by Django 4.1.5 on 2023-03-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deparment',
        ),
    ]
