# Generated by Django 4.1.5 on 2023-02-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_companydetails_registration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='tin_no',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
