# Generated by Django 4.1.5 on 2023-11-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_employeeprofessionaldetail_category_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['employee'], name='api_employe_employe_a0f66c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['date'], name='api_employe_date_be437c_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['company_id'], name='api_employe_company_8acfd4_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeattendance',
            index=models.Index(fields=['user'], name='api_employe_user_id_ed82f0_idx'),
        ),
        migrations.AddIndex(
            model_name='employeegenerativeleaverecord',
            index=models.Index(fields=['employee'], name='api_employe_employe_c5ed79_idx'),
        ),
        migrations.AddIndex(
            model_name='employeegenerativeleaverecord',
            index=models.Index(fields=['date'], name='api_employe_date_991c79_idx'),
        ),
        migrations.AddIndex(
            model_name='employeegenerativeleaverecord',
            index=models.Index(fields=['company_id'], name='api_employe_company_93d215_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemonthlyattendancedetails',
            index=models.Index(fields=['employee'], name='api_employe_employe_13a192_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemonthlyattendancedetails',
            index=models.Index(fields=['date'], name='api_employe_date_5c7dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='employeemonthlyattendancedetails',
            index=models.Index(fields=['company_id'], name='api_employe_company_4db296_idx'),
        ),
    ]
