# Generated by Django 4.1.5 on 2023-04-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('REGULAR', 'Regular')], default='OWNER', max_length=50),
        ),
    ]
