# Generated by Django 4.1.5 on 2023-11-21 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employeeattendance_api_employe_employe_a0f66c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalaryprepared',
            name='holiday_days_count',
        ),
        migrations.RemoveField(
            model_name='employeesalaryprepared',
            name='not_paid_days_count',
        ),
        migrations.RemoveField(
            model_name='employeesalaryprepared',
            name='paid_days_count',
        ),
        migrations.RemoveField(
            model_name='employeesalaryprepared',
            name='present_count',
        ),
        migrations.RemoveField(
            model_name='employeesalaryprepared',
            name='weekly_off_days_count',
        ),
    ]
