# Generated by Django 4.1.5 on 2023-11-27 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_employeesalaryprepared_holiday_days_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfesisetup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_companies_pf_esi_setup_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
