# Generated by Django 4.1.5 on 2023-05-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ownertoregular_owner_alter_ownertoregular_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
