# Generated by Django 5.0 on 2023-12-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_employeeattendance_first_half_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeeattendance',
            name='unique_employee_attendance_date_wise',
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_attendance_date_wise'),
        ),
    ]
