# Generated by Django 5.0 on 2023-12-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_employeeattendance_unique_employee_attendance_date_wise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='first_previous_experience_company_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='first_previous_experience_designation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='first_previous_experience_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='first_previous_experience_reason_for_leaving',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='first_previous_experience_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='first_previous_experience_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='first_reference_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='first_reference_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='first_reference_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='first_reference_relation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='second_previous_experience_company_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='second_previous_experience_designation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='second_previous_experience_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='second_previous_experience_reason_for_leaving',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='second_previous_experience_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='second_previous_experience_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='second_reference_address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='second_reference_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='second_reference_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='second_reference_relation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='third_previous_experience_company_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='third_previous_experience_designation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='third_previous_experience_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='third_previous_experience_reason_for_leaving',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='third_previous_experience_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='third_previous_experience_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
