# Generated by Django 5.0 on 2023-12-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_employeeprofessionaldetail_first_previous_experience_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonaldetail',
            name='nationality',
            field=models.CharField(default='Indian', max_length=50),
        ),
    ]
