# Generated by Django 5.0 on 2023-12-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_employeepersonaldetail_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='lunch_time',
            new_name='lunch_duration',
        ),
        migrations.AddField(
            model_name='shift',
            name='lunch_beginning_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
