# Generated by Django 4.1.5 on 2023-06-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_leavegrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavegrade',
            name='mandatory_leave',
            field=models.BooleanField(default=False),
        ),
    ]
