# Generated by Django 5.0 on 2024-01-10 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_company_name_company_unique_company_for_a_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculations',
            name='bonus_start_month',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
