# Generated by Django 4.1.5 on 2023-06-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_leavegrade_unique_leave_grade_name_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leavegrade',
            name='unique_leave_grade_name_per_user',
        ),
    ]
