# Generated by Django 5.0 on 2024-01-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bonuscalculation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonusCalculation',
        ),
    ]
