# Generated by Django 4.1.5 on 2023-06-15 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_leavegrade_unique_leave_grade_name_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('beginning_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('lunch_time', models.PositiveSmallIntegerField(default=0)),
                ('tea_time', models.PositiveSmallIntegerField(default=0)),
                ('ot_begin_after', models.PositiveSmallIntegerField(default=0)),
                ('half_day_minimum_minutes', models.PositiveSmallIntegerField()),
                ('full_day_minimum_minutes', models.PositiveSmallIntegerField()),
                ('short_leaves', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'name'), name='unique_shift_name_per_user'),
        ),
    ]
