# Generated by Django 5.0 on 2024-01-11 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_bonuscalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='same_category_bonus_calculation', to='api.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_calculation', to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_company_bonus_calculation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='bonuscalculation',
            constraint=models.UniqueConstraint(fields=('company', 'date', 'category'), name='unique_bonus_calculation_for_each_month'),
        ),
    ]
