# Generated by Django 4.1.5 on 2023-06-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_shift_shift_unique_shift_name_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='accidental_punch_buffer',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='next_shift_dealy',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
