# Generated by Django 4.1.5 on 2023-06-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_shift_accidental_punch_buffer_shift_next_shift_dealy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='full_day_minimum_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='half_day_minimum_minutes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
