# Generated by Django 4.1.5 on 2023-06-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_shift_full_day_minimum_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='late_grace',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='full_day_minimum_minutes',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='half_day_minimum_minutes',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
