# Generated by Django 5.0 on 2024-01-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_bonuspercentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculations',
            name='bonus_calculation_days',
            field=models.CharField(choices=[('26', '26'), ('30', '30'), ('month_days', 'month_days')], default='month_days', max_length=10),
        ),
    ]
