# Generated by Django 4.1.5 on 2023-06-24 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_holiday_holiday_unique_hodiday_name_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningsHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_heads', to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_heads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
