# Generated by Django 5.0 on 2024-01-19 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_calculations_bonus_calculation_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullAndFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_and_final_date', models.DateField()),
                ('el_encashment_days', models.SmallIntegerField(default=0)),
                ('el_encashment_amount', models.SmallIntegerField(default=0)),
                ('bonus_prev_year', models.PositiveIntegerField(default=0)),
                ('bonus_current_year', models.PositiveIntegerField(default=0)),
                ('gratuity', models.PositiveIntegerField(default=0)),
                ('service_compensation_days', models.PositiveSmallIntegerField(default=0)),
                ('service_compensation_amount', models.PositiveIntegerField(default=0)),
                ('earnings_notice_period_days', models.PositiveSmallIntegerField(default=0)),
                ('earnings_notice_period_amount', models.PositiveIntegerField(default=0)),
                ('ot_min', models.PositiveIntegerField(default=0)),
                ('ot_amount', models.PositiveIntegerField(default=0)),
                ('earnings_others', models.PositiveIntegerField(default=0)),
                ('deductions_notice_period_days', models.PositiveSmallIntegerField(default=0)),
                ('deductions_notice_period_amount', models.PositiveIntegerField(default=0)),
                ('deductions_others', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_employees_full_and_final', to='api.company')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='full_and_final', to='api.employeepersonaldetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_company_employees_full_and_final', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
