# Generated by Django 5.0 on 2024-01-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_fullandfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculations',
            name='gratuity_salary',
            field=models.CharField(choices=[('basic', 'basic'), ('gross', 'gross')], default='gross', max_length=5),
        ),
    ]
