# Generated by Django 4.1.5 on 2023-06-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_mandatory_deductions_deductionshead_mandatory_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningshead',
            name='mandatory_earning',
            field=models.BooleanField(default=False),
        ),
    ]
