# Generated by Django 5.0 on 2024-01-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_user_subscription_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonaldetail',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
