# Generated by Django 4.1.5 on 2023-06-27 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_earningshead_mandatory_earning'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CT', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('JK', 'Jammu and Kashmir'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('LD', 'Lakshadweep'), ('PY', 'Puducherry')], max_length=2)),
                ('name', models.CharField(max_length=256)),
                ('paycode', models.PositiveSmallIntegerField()),
                ('attendance_card_no', models.PositiveSmallIntegerField()),
                ('father_or_husband_name', models.CharField(blank=True, max_length=256, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=256, null=True)),
                ('wife_name', models.CharField(blank=True, max_length=256, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('driving_licence', models.CharField(blank=True, max_length=15, null=True)),
                ('passport', models.CharField(blank=True, max_length=8, null=True)),
                ('aadhaar', models.CharField(blank=True, max_length=12, null=True)),
                ('handicapped', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], max_length=1, null=True)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('education_qualification', models.CharField(blank=True, choices=[('0', 'No Qualification'), ('1', '1st class'), ('2', '2nd class'), ('3', '3rd class'), ('4', '4th class'), ('5', '5th class'), ('6', '6th class'), ('7', '7th class'), ('8', '8th class'), ('9', '9th class'), ('10', '10th class'), ('11', '11th class'), ('12', '12th class')], max_length=2, null=True)),
                ('technical_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('local_address', models.CharField(blank=True, max_length=256, null=True)),
                ('local_district', models.CharField(blank=True, max_length=30, null=True)),
                ('local_state_or_union_territory', models.CharField(blank=True, choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CT', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('JK', 'Jammu and Kashmir'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('LD', 'Lakshadweep'), ('PY', 'Puducherry')], max_length=2, null=True)),
                ('local_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=256, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=30, null=True)),
                ('permanent_state_or_union_territory', models.CharField(blank=True, choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CT', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal'), ('JK', 'Jammu and Kashmir'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('LD', 'Lakshadweep'), ('PY', 'Puducherry')], max_length=2, null=True)),
                ('permanent_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='deductionshead',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'name'), name='unique_deductions_head_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='earningshead',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'name'), name='unique_earnings_head_name_per_user'),
        ),
        migrations.AddField(
            model_name='employeepersonaldetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_personal_detail', to='api.company'),
        ),
        migrations.AddField(
            model_name='employeepersonaldetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_personal_detail', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='employeepersonaldetail',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'paycode'), name='unique_paycode_per_employee_within_each_company_and_user'),
        ),
        migrations.AddConstraint(
            model_name='employeepersonaldetail',
            constraint=models.UniqueConstraint(fields=('user', 'company', 'attendance_card_no'), name='unique_attendance_card_no_per_employee_within_each_company_and_user'),
        ),
    ]
