# Generated by Django 4.1.5 on 2023-06-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_employeepersonaldetail_alter_companydetails_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonaldetail',
            name='employee_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
