# Generated by Django 5.0 on 2024-01-29 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_ownertoregular_owner_alter_ownertoregular_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownertoregular',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_to_regular', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownertoregular',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regular_to_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
