# Generated by Django 4.1.5 on 2023-06-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_employeepersonaldetail_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='state',
        ),
    ]
