# Generated by Django 5.0 on 2024-01-30 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_ownertoregular_owner_alter_ownertoregular_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofessionaldetail',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='same_category_employees', to='api.category'),
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetail',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='same_department_employees', to='api.deparment'),
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetail',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='same_designation_employees', to='api.designation'),
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetail',
            name='salary_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='same_salary_grade_employees', to='api.salarygrade'),
        ),
    ]
