# Generated by Django 4.1.5 on 2023-06-29 01:28

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_employeepersonaldetail_blood_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='employee_photo',
        ),
        migrations.CreateModel(
            name='EmployeePhoto',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_photo', serialize=False, to='api.employeepersonaldetail')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=api.models.employee_photo_handler)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_photos', to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
