# Generated by Django 4.1.5 on 2023-06-29 15:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_employeepersonaldetail_employee_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='aadhaar',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='alternate_phone_number',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='driving_licence',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='education_qualification',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='father_or_husband_name',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='handicapped',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='local_address',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='local_district',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='local_pincode',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='local_state_or_union_territory',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='permanent_district',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='permanent_pincode',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='permanent_state_or_union_territory',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='technical_qualification',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetail',
            name='wife_name',
        ),
        migrations.AddField(
            model_name='employeepersonaldetail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.employee_photo_handler),
        ),
        migrations.DeleteModel(
            name='EmployeePhoto',
        ),
    ]
