# Generated by Django 4.1.5 on 2023-06-30 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_employeepersonaldetail_aadhaar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonaldetail',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 0, 0)),
        ),
    ]
