# Generated by Django 5.0 on 2024-02-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_subuserovertimesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubUserOvertimeSettings',
        ),
    ]
