# Generated by Django 4.1.5 on 2023-06-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_employeepersonaldetail_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonaldetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
