# Generated by Django 5.0 on 2024-02-10 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_subuserovertimesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUserMiscSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('female_ot_allow', models.BooleanField(default=False)),
                ('max_female_ot', models.PositiveSmallIntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_user_misc_settings', to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_user_misc_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
