# Generated by Django 5.0 on 2024-02-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_subusermiscsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subusermiscsettings',
            name='max_female_ot',
        ),
        migrations.AddField(
            model_name='subusermiscsettings',
            name='max_female_punch_out',
            field=models.TimeField(default='19:00'),
        ),
    ]
