# Generated by Django 5.0 on 2024-02-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_subusermiscsettings_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeeattendance',
            name='unique_employee_attendance_date_wise',
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date', 'user'), name='unique_employee_attendance_date_wise'),
        ),
    ]
