# Generated by Django 4.1.5 on 2023-07-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_employeeprofessionaldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofessionaldetail',
            name='extra_off',
            field=models.CharField(choices=[('2_sat', '2nd Saturday'), ('4_sat', '4th Saturday'), ('2_4_sat', 'Second and Last Saturday'), ('no_off', 'No Off')], default='no_off', max_length=10),
        ),
    ]
