# Generated by Django 4.1.5 on 2023-07-03 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_employeeprofessionaldetail_extra_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonaldetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_personal_details', to='api.company'),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_personal_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetail',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_professional_details', to='api.company'),
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetail',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_professional_details', to='api.employeepersonaldetail'),
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_professional_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
