# Generated by Django 5.0 on 2024-02-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_employeeattendance_unique_employee_attendance_date_wise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subusermiscsettings',
            old_name='female_ot_allow',
            new_name='enable_female_max_punch_out',
        ),
    ]
