# Generated by Django 5.0 on 2024-02-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_female_ot_allow_subusermiscsettings_enable_female_max_punch_out'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeegenerativeleaverecord',
            name='unique_date_per_employee_per_company',
        ),
        migrations.AddConstraint(
            model_name='employeegenerativeleaverecord',
            constraint=models.UniqueConstraint(fields=('employee', 'date', 'company', 'leave', 'user'), name='unique_date_per_employee_per_company_per_user'),
        ),
    ]
