# Generated by Django 4.1.5 on 2023-07-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_employeepersonaldetail_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofessionaldetail',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_professional_detail', to='api.employeepersonaldetail'),
        ),
    ]
