# Generated by Django 5.0 on 2024-02-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_employeegenerativeleaverecord_unique_date_per_employee_per_company_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeeleaveopening',
            name='unique_year_per_employee_per_company',
        ),
        migrations.AddConstraint(
            model_name='employeeleaveopening',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'company', 'user'), name='unique_year_per_employee_per_company_per_user'),
        ),
    ]
