# Generated by Django 5.0 on 2024-02-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_employeeleaveopening_unique_year_per_employee_per_company_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeesalaryprepared',
            name='unique_salary_for_each_month',
        ),
        migrations.AddConstraint(
            model_name='employeesalaryprepared',
            constraint=models.UniqueConstraint(fields=('date', 'employee', 'user'), name='unique_salary_for_each_month_per_employee_per_user'),
        ),
    ]
