# Generated by Django 4.1.5 on 2023-07-03 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_employeeprofessionaldetail_weekly_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofessionaldetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeeprofessionaldetail',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_professional_detail', serialize=False, to='api.employeepersonaldetail'),
        ),
    ]
