# Generated by Django 5.0 on 2024-03-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_remove_employeesalaryprepared_unique_salary_for_each_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullandfinal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_and_final', to='api.employeepersonaldetail'),
        ),
        migrations.AddConstraint(
            model_name='fullandfinal',
            constraint=models.UniqueConstraint(fields=('user', 'employee'), name='unique_full_and_final_per_employee_per_user'),
        ),
    ]
