# Generated by Django 4.1.5 on 2023-07-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_employeeprofessionaldetail_extra_off'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofessionaldetail',
            name='weekly_off',
            field=models.CharField(choices=[('no_off', 'No Off'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], default='no_off', max_length=6),
        ),
    ]
