# Generated by Django 5.0 on 2024-04-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_remove_employeeleaveopening_unique_year_per_employee_per_company_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaveopening',
            name='leave_count',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
