# Generated by Django 4.1.5 on 2023-07-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_employeeprofessionaldetail_weekly_off_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalaryearnings',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employeesalaryearnings',
            name='earnings_head',
        ),
        migrations.RemoveField(
            model_name='employeesalaryearnings',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeesalaryearnings',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmployeeSalaryDetails',
        ),
        migrations.DeleteModel(
            name='EmployeeSalaryEarnings',
        ),
    ]
