# Generated by Django 4.1.5 on 2023-07-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_employeesalaryearnings_employeesalarydetails_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSalaryEarnings',
        ),
    ]
