# Generated by Django 5.0 on 2024-10-22 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_employeeleaveopening_leave_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMachineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_machine_configuration', to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_machine_configuration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
