# Generated by Django 4.1.5 on 2023-07-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_delete_employeesalaryearnings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSalaryDetails',
        ),
    ]
