# Generated by Django 5.0 on 2026-07-26 19:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


STANDARD_POLICIES = (
    ('No overtime', 'NO_OVERTIME', (), True),
    ('All days - single rate', 'ALL_DAYS_SINGLE', (('REGULAR', Decimal('1')), ('WEEKLY_OFF', Decimal('1')), ('HOLIDAY', Decimal('1'))), False),
    ('WO/HD - single rate', 'WO_HD_SINGLE', (('WEEKLY_OFF', Decimal('1')), ('HOLIDAY', Decimal('1'))), False),
    ('All days - double rate', 'ALL_DAYS_DOUBLE', (('REGULAR', Decimal('2')), ('WEEKLY_OFF', Decimal('2')), ('HOLIDAY', Decimal('2'))), False),
    ('WO/HD - double rate', 'WO_HD_DOUBLE', (('WEEKLY_OFF', Decimal('2')), ('HOLIDAY', Decimal('2'))), False),
)


LEGACY_POLICY_CODE_BY_SETTINGS = {
    ('no_overtime', None): 'NO_OVERTIME',
    ('no_overtime', ''): 'NO_OVERTIME',
    ('no_overtime', 'S'): 'NO_OVERTIME',
    ('no_overtime', 'D'): 'NO_OVERTIME',
    ('all_days', None): 'ALL_DAYS_SINGLE',
    ('all_days', ''): 'ALL_DAYS_SINGLE',
    ('all_days', 'S'): 'ALL_DAYS_SINGLE',
    ('all_days', 'D'): 'ALL_DAYS_DOUBLE',
    ('holiday_weekly_off', None): 'WO_HD_SINGLE',
    ('holiday_weekly_off', ''): 'WO_HD_SINGLE',
    ('holiday_weekly_off', 'S'): 'WO_HD_SINGLE',
    ('holiday_weekly_off', 'D'): 'WO_HD_DOUBLE',
}


def create_and_assign_overtime_policies(apps, schema_editor):
    Company = apps.get_model('api', 'Company')
    EmployeeSalaryDetail = apps.get_model('api', 'EmployeeSalaryDetail')
    OvertimePolicy = apps.get_model('api', 'OvertimePolicy')
    OvertimePolicyDayRule = apps.get_model('api', 'OvertimePolicyDayRule')

    unknown_settings = []
    for company in Company.objects.all():
        policies = {}
        existing_default = OvertimePolicy.objects.filter(company=company, is_default=True, is_active=True).first()
        for name, code, rules, is_default in STANDARD_POLICIES:
            policy, _ = OvertimePolicy.objects.get_or_create(
                company=company,
                code=code,
                defaults={
                    'name': name,
                    'is_default': is_default and existing_default is None,
                    'is_active': True,
                    'is_system': True,
                    'earnings_basis': 'ALL_EARNINGS',
                },
            )
            policies[code] = policy
            for priority, (day_type, multiplier) in enumerate(rules, start=1):
                OvertimePolicyDayRule.objects.update_or_create(
                    policy=policy,
                    day_type=day_type,
                    defaults={
                        'multiplier': multiplier,
                        'late_deduction_priority': priority,
                    },
                )

        for salary_detail in EmployeeSalaryDetail.objects.filter(company=company):
            key = (salary_detail.overtime_type, salary_detail.overtime_rate)
            code = LEGACY_POLICY_CODE_BY_SETTINGS.get(key)
            if code is None:
                unknown_settings.append(f'employee={salary_detail.employee_id}, company={company.id}, overtime_type={key[0]!r}, overtime_rate={key[1]!r}')
                continue
            salary_detail.overtime_policy = policies[code]
            salary_detail.save(update_fields=['overtime_policy'])

    if unknown_settings:
        raise RuntimeError('Unknown overtime settings found: ' + '; '.join(unknown_settings))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_extrafeaturesconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryPreparedOvertimeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.CharField(choices=[('REGULAR', 'Regular'), ('WEEKLY_OFF', 'Weekly Off'), ('HOLIDAY', 'Holiday')], max_length=20)),
                ('gross_minutes', models.PositiveSmallIntegerField(default=0)),
                ('deducted_late_minutes', models.PositiveSmallIntegerField(default=0)),
                ('net_minutes', models.PositiveSmallIntegerField(default=0)),
                ('multiplier', models.DecimalField(decimal_places=3, max_digits=6)),
                ('eligible_salary_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('divisor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('salary_prepared', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_breakdown', to='api.employeesalaryprepared')),
            ],
        ),
        migrations.CreateModel(
            name='OvertimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('earnings_basis', models.CharField(choices=[('ALL_EARNINGS', 'All Earnings'), ('SELECTED_HEADS', 'Selected Heads')], default='ALL_EARNINGS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_policies', to='api.company')),
            ],
        ),
        migrations.AddField(
            model_name='employeesalarydetail',
            name='overtime_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_salary_details', to='api.overtimepolicy'),
        ),
        migrations.CreateModel(
            name='OvertimePolicyDayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.CharField(choices=[('REGULAR', 'Regular'), ('WEEKLY_OFF', 'Weekly Off'), ('HOLIDAY', 'Holiday')], max_length=20)),
                ('multiplier', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('late_deduction_priority', models.PositiveSmallIntegerField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_rules', to='api.overtimepolicy')),
            ],
            options={
                'ordering': ['late_deduction_priority', 'day_type'],
            },
        ),
        migrations.RunPython(create_and_assign_overtime_policies, noop_reverse),
        migrations.CreateModel(
            name='OvertimePolicyEarningsHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overtime_policies', to='api.earningshead')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_earning_heads', to='api.overtimepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAttendanceOvertimeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('day_type', models.CharField(choices=[('REGULAR', 'Regular'), ('WEEKLY_OFF', 'Weekly Off'), ('HOLIDAY', 'Holiday')], max_length=20)),
                ('source', models.CharField(choices=[('EARLY_ARRIVAL', 'Early Arrival'), ('LATE_DEPARTURE', 'Late Departure'), ('OFF_DAY_WORK', 'Off Day Work'), ('MANUAL', 'Manual'), ('IMPORTED', 'Imported')], max_length=20)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('gross_minutes', models.PositiveSmallIntegerField()),
                ('excluded_minutes', models.PositiveSmallIntegerField(default=0)),
                ('eligible_minutes', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_details', to='api.employeeattendance')),
            ],
            options={
                'indexes': [models.Index(fields=['attendance', 'work_date', 'day_type'], name='api_employe_attenda_535638_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='employeeattendanceovertimedetail',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('end_datetime__isnull', True), ('start_datetime__isnull', True)), models.Q(('end_datetime__isnull', False), ('start_datetime__isnull', False)), _connector='OR'), name='attendance_ot_detail_datetimes_both_set_or_null'),
        ),
        migrations.AddConstraint(
            model_name='employeeattendanceovertimedetail',
            constraint=models.CheckConstraint(check=models.Q(('gross_minutes__gt', 0)), name='attendance_ot_detail_gross_positive'),
        ),
        migrations.AddConstraint(
            model_name='employeeattendanceovertimedetail',
            constraint=models.CheckConstraint(check=models.Q(('excluded_minutes__lte', models.F('gross_minutes'))), name='attendance_ot_detail_excluded_lte_gross'),
        ),
        migrations.AddConstraint(
            model_name='employeeattendanceovertimedetail',
            constraint=models.CheckConstraint(check=models.Q(('eligible_minutes__gt', 0)), name='attendance_ot_detail_eligible_positive'),
        ),
        migrations.AddConstraint(
            model_name='employeesalarypreparedovertimedetail',
            constraint=models.UniqueConstraint(fields=('salary_prepared', 'day_type'), name='unique_salary_prepared_overtime_day_type'),
        ),
        migrations.AddConstraint(
            model_name='employeesalarypreparedovertimedetail',
            constraint=models.CheckConstraint(check=models.Q(('gross_minutes__gte', models.F('deducted_late_minutes'))), name='prepared_ot_gross_gte_deducted'),
        ),
        migrations.AddConstraint(
            model_name='overtimepolicy',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_overtime_policy_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='overtimepolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('company',), name='unique_active_default_overtime_policy_per_company'),
        ),
        migrations.AddConstraint(
            model_name='overtimepolicydayrule',
            constraint=models.UniqueConstraint(fields=('policy', 'day_type'), name='unique_overtime_policy_day_type'),
        ),
        migrations.AddConstraint(
            model_name='overtimepolicydayrule',
            constraint=models.UniqueConstraint(fields=('policy', 'late_deduction_priority'), name='unique_overtime_policy_late_priority'),
        ),
        migrations.AddConstraint(
            model_name='overtimepolicyearningshead',
            constraint=models.UniqueConstraint(fields=('policy', 'earnings_head'), name='unique_overtime_policy_earning_head'),
        ),
    ]
