# Generated by Django 4.1.5 on 2023-07-08 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_delete_employeesalarydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_company_employees_earnings', to='api.company')),
                ('earnings_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_earnings', to='api.earningshead')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='api.employeepersonaldetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_employees_earnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalaryDetails',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_salary_detail', serialize=False, to='api.employeepersonaldetail')),
                ('overtime_type', models.CharField(choices=[('no_overtime', 'No Overtime'), ('all_days', 'All Days'), ('holiday_weekly_off', 'Holiday/Weekly Off')], default='no_overtime', max_length=20)),
                ('overtime_rate', models.CharField(choices=[('S', 'Single'), ('D', 'Double')], default='S', max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_details', to='api.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='employeesalaryearnings',
            constraint=models.UniqueConstraint(fields=('employee', 'earnings_head'), name='unique_employee_earning_head'),
        ),
    ]
