# Generated by Django 4.1.5 on 2023-07-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_employeesalaryearnings_employeesalarydetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalarydetails',
            name='overtime_rate',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('D', 'Double')], max_length=1, null=True),
        ),
    ]
