# Generated by Django 5.0 on 2026-08-08 15:15

import api.models
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models
from django.db.models import F
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError


def initialize_phase_two_defaults(apps, schema_editor):
    try:
        payroll_timezone = settings.PAYROLL_DEFAULT_TIMEZONE
        ZoneInfo(payroll_timezone)
    except (AttributeError, ZoneInfoNotFoundError, ValueError, TypeError) as exc:
        raise RuntimeError('PAYROLL_DEFAULT_TIMEZONE must be a valid IANA timezone name.') from exc

    Company = apps.get_model('api', 'Company')
    CompanyDetails = apps.get_model('api', 'CompanyDetails')
    OvertimePolicy = apps.get_model('api', 'OvertimePolicy')

    CompanyDetails.objects.update(payroll_timezone=payroll_timezone)
    for company in Company.objects.all().iterator():
        CompanyDetails.objects.get_or_create(
            company=company,
            defaults={'user_id': company.user_id, 'payroll_timezone': payroll_timezone},
        )
    OvertimePolicy.objects.update(
        rounding_increment_minutes=30,
        round_up_from_minutes=16,
    )


def preflight_phase_two_constraints(apps, schema_editor):
    AttendanceDetail = apps.get_model('api', 'EmployeeAttendanceOvertimeDetail')
    PreparedDetail = apps.get_model('api', 'EmployeeSalaryPreparedOvertimeDetail')
    checks = {
        'attendance_start_before_end': AttendanceDetail.objects.filter(
            start_datetime__isnull=False,
            end_datetime__lte=F('start_datetime'),
        ),
        'attendance_eligible_arithmetic': AttendanceDetail.objects.exclude(
            eligible_minutes=F('gross_minutes') - F('excluded_minutes'),
        ),
        'prepared_net_arithmetic': PreparedDetail.objects.exclude(
            net_minutes=F('gross_minutes') - F('deducted_late_minutes'),
        ),
        'prepared_multiplier_positive': PreparedDetail.objects.filter(multiplier__lte=0),
        'prepared_divisor_positive': PreparedDetail.objects.filter(divisor__lte=0),
    }
    failures = []
    for name, queryset in checks.items():
        invalid_ids = list(queryset.order_by('id').values_list('id', flat=True))
        if invalid_ids:
            failures.append(f'{name} IDs: {invalid_ids}')
    if failures:
        raise RuntimeError('Phase 2 constraint preflight failed. ' + '; '.join(failures))


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_overtime_policy_active_default_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='payroll_timezone',
            field=models.CharField(default=api.models.get_default_payroll_timezone, max_length=63, validators=[api.models.validate_iana_timezone]),
        ),
        migrations.AddField(
            model_name='employeesalaryprepared',
            name='ot_round_up_from_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeesalaryprepared',
            name='ot_rounding_increment_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimepolicy',
            name='round_up_from_minutes',
            field=models.PositiveSmallIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='overtimepolicy',
            name='rounding_increment_minutes',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.RunPython(initialize_phase_two_defaults, noop_reverse),
        migrations.RunPython(preflight_phase_two_constraints, noop_reverse),
        migrations.AddConstraint(
            model_name='employeesalaryprepared',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ot_round_up_from_minutes__isnull', True), ('ot_rounding_increment_minutes__isnull', True)), models.Q(('ot_round_up_from_minutes__gte', 1), ('ot_round_up_from_minutes__isnull', False), ('ot_round_up_from_minutes__lte', models.F('ot_rounding_increment_minutes')), ('ot_rounding_increment_minutes__gt', 0), ('ot_rounding_increment_minutes__isnull', False)), _connector='OR'), name='prepared_salary_rounding_pair_valid'),
        ),
        migrations.AddConstraint(
            model_name='employeesalarypreparedovertimedetail',
            constraint=models.CheckConstraint(check=models.Q(('net_minutes', django.db.models.expressions.CombinedExpression(models.F('gross_minutes'), '-', models.F('deducted_late_minutes')))), name='prepared_ot_net_arithmetic'),
        ),
        migrations.AddConstraint(
            model_name='employeesalarypreparedovertimedetail',
            constraint=models.CheckConstraint(check=models.Q(('multiplier__gt', 0)), name='prepared_ot_multiplier_positive'),
        ),
        migrations.AddConstraint(
            model_name='employeesalarypreparedovertimedetail',
            constraint=models.CheckConstraint(check=models.Q(('divisor__gt', 0)), name='prepared_ot_divisor_positive'),
        ),
        migrations.AddConstraint(
            model_name='overtimepolicy',
            constraint=models.CheckConstraint(check=models.Q(('rounding_increment_minutes__gt', 0)), name='overtime_policy_rounding_increment_positive'),
        ),
        migrations.AddConstraint(
            model_name='overtimepolicy',
            constraint=models.CheckConstraint(check=models.Q(('round_up_from_minutes__gte', 1)), name='overtime_policy_round_up_positive'),
        ),
        migrations.AddConstraint(
            model_name='overtimepolicy',
            constraint=models.CheckConstraint(check=models.Q(('round_up_from_minutes__lte', models.F('rounding_increment_minutes'))), name='overtime_policy_round_up_lte_increment'),
        ),
    ]
