# Generated by Django 4.1.5 on 2023-07-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_employeesalarydetails_account_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeSalaryDetails',
            new_name='EmployeeSalaryDetail',
        ),
        migrations.RenameModel(
            old_name='EmployeeSalaryEarnings',
            new_name='EmployeeSalaryEarning',
        ),
    ]
