# Generated by Django 4.1.5 on 2023-07-12 08:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_rename_employeesalarydetails_employeesalarydetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFamilyNomineeDetial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('relation', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Wife', 'Wife'), ('Son', 'Son'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Daughter', 'Daughter'), ('Husband', 'Husband')], max_length=10)),
                ('residing', models.BooleanField(default=True)),
                ('esi_benefit', models.BooleanField(default=True)),
                ('pf_benefits', models.BooleanField(default=True)),
                ('is_esi_nominee', models.BooleanField(default=False)),
                ('esi_nominee_share', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_pf_nominee', models.BooleanField(default=False)),
                ('pf_nominee_share', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_fa_nominee', models.BooleanField(default=False)),
                ('fa_nominee_share', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_gratuity_nominee', models.BooleanField(default=False)),
                ('gratuity_nominee_share', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_family_nominee_details', to='api.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_family_nominee_detail', to='api.employeepersonaldetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_family_nominee_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
