# Generated by Django 4.1.5 on 2023-07-13 08:37

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_employeefamilynomineedetial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePfEsiDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_allow', models.BooleanField(default=False)),
                ('pf_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pf_limit_ignore_employee', models.BooleanField(default=False)),
                ('pf_limit_ignore_employee_value', models.PositiveIntegerField(blank=True, null=True)),
                ('pf_limit_ignore_employer', models.BooleanField(default=False)),
                ('pf_limit_ignore_employer_value', models.BooleanField(default=False)),
                ('pf_percent_ignore_employee', models.BooleanField(default=False)),
                ('pf_percent_ignore_employee_value', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pf_percent_ignore_employer', models.BooleanField(default=False)),
                ('pf_percent_ignore_employer_value', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('uan_number', models.CharField(blank=True, max_length=30, null=True)),
                ('esi_allow', models.BooleanField(default=False)),
                ('esi_number', models.CharField(blank=True, max_length=30, null=True)),
                ('esi_dispensary', models.CharField(blank=True, max_length=100, null=True)),
                ('esi_on_ot', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_pf_esi_details', to='api.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_pf_esi_detail', to='api.employeepersonaldetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_pf_esi_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
