# Generated by Django 4.1.5 on 2023-07-13 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_employeepfesidetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepfesidetail',
            name='pf_limit_ignore_employer_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeepfesidetail',
            name='pf_percent_ignore_employee_value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='employeepfesidetail',
            name='pf_percent_ignore_employer_value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
