# Generated by Django 5.0 on 2026-08-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_regular_days_overtime_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalarypreparedovertimedetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
