# Generated by Django 4.1.5 on 2023-07-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_alter_employeepfesidetail_pf_limit_ignore_employer_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepfesidetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='employeepfesidetail',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_pf_esi_detail', serialize=False, to='api.employeepersonaldetail'),
        ),
    ]
