# Generated by Django 4.1.5 on 2023-07-14 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_remove_employeepfesidetail_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefamilynomineedetial',
            name='esi_nominee_share',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='employeefamilynomineedetial',
            name='fa_nominee_share',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='employeefamilynomineedetial',
            name='gratuity_nominee_share',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='employeefamilynomineedetial',
            name='pf_nominee_share',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='employeepfesidetail',
            name='pf_percent_ignore_employee_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='employeepfesidetail',
            name='pf_percent_ignore_employer_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
