# Generated by Django 4.1.5 on 2023-07-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_employeefamilynomineedetial_esi_nominee_share_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeesalaryearning',
            name='unique_employee_earning_head',
        ),
        migrations.AddField(
            model_name='employeesalaryearning',
            name='month',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employeesalaryearning',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023),
        ),
        migrations.AddConstraint(
            model_name='employeesalaryearning',
            constraint=models.UniqueConstraint(fields=('employee', 'earnings_head', 'month', 'year'), name='unique_employee_earning_head'),
        ),
    ]
