# Generated by Django 4.1.5 on 2023-07-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_remove_employeesalaryearning_unique_employee_earning_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalaryearning',
            name='month',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='employeesalaryearning',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
