# Generated by Django 4.1.5 on 2023-07-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_employeesalaryearning_month_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeesalaryearning',
            name='unique_employee_earning_head',
        ),
        migrations.RemoveField(
            model_name='employeesalaryearning',
            name='month',
        ),
        migrations.AddConstraint(
            model_name='employeesalaryearning',
            constraint=models.UniqueConstraint(fields=('employee', 'earnings_head', 'year'), name='unique_employee_earning_head'),
        ),
    ]
