# Generated by Django 4.1.5 on 2023-07-19 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_remove_employeesalaryearning_unique_employee_earning_head_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMonthlySalaryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_company_employees_monthly_salary_changes', to='api.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_salary_changes', to='api.employeepersonaldetail')),
                ('salary_earnings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_changes', to='api.employeesalaryearning')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_employees_monthly_salary_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='employeemonthlysalarychange',
            constraint=models.UniqueConstraint(fields=('employee', 'month', 'salary_earnings'), name='unique_employee_monthly_salary'),
        ),
    ]
