# Generated by Django 4.1.5 on 2023-07-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_delete_employeemonthlysalarychange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalaryearning',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeesalaryearning',
            name='to_date',
            field=models.DateField(),
        ),
    ]
