# Generated by Django 4.1.5 on 2023-07-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_weeklyoffholidayoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyoffholidayoff',
            name='id',
        ),
        migrations.AlterField(
            model_name='weeklyoffholidayoff',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='weekly_off_holiday_off_entry', serialize=False, to='api.company'),
        ),
    ]
