# Generated by Django 4.1.5 on 2023-08-02 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_pfesisetup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfesisetup',
            name='id',
        ),
        migrations.AlterField(
            model_name='pfesisetup',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pf_esi_setup_details', serialize=False, to='api.company'),
        ),
    ]
