# Generated by Django 4.1.5 on 2023-08-03 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_pfesisetup_id_alter_pfesisetup_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pfesisetup',
            old_name='ac10_eps_employer_value',
            new_name='ac10_eps_employer_limit',
        ),
    ]
