# Generated by Django 4.1.5 on 2023-08-03 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_rename_ac10_eps_employer_value_pfesisetup_ac10_eps_employer_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pfesisetup',
            old_name='ac10_eps_employer_limit',
            new_name='ac_10_eps_employer_limit',
        ),
        migrations.RenameField(
            model_name='pfesisetup',
            old_name='ac10_eps_employer_percentage',
            new_name='ac_10_eps_employer_percentage',
        ),
        migrations.RenameField(
            model_name='pfesisetup',
            old_name='ac1_epf_employee_limit',
            new_name='ac_1_epf_employee_limit',
        ),
        migrations.RenameField(
            model_name='pfesisetup',
            old_name='ac1_epf_employee_percentage',
            new_name='ac_1_epf_employee_percentage',
        ),
        migrations.RenameField(
            model_name='pfesisetup',
            old_name='ac1_epf_employer_limit',
            new_name='ac_1_epf_employer_limit',
        ),
        migrations.RenameField(
            model_name='pfesisetup',
            old_name='ac1_epf_employer_percentage',
            new_name='ac_1_epf_employer_percentage',
        ),
        migrations.RenameField(
            model_name='pfesisetup',
            old_name='ac21_employer_percentage',
            new_name='ac_21_employer_percentage',
        ),
        migrations.RenameField(
            model_name='pfesisetup',
            old_name='ac22_employer_percentage',
            new_name='ac_22_employer_percentage',
        ),
        migrations.RenameField(
            model_name='pfesisetup',
            old_name='ac2_employer_percentage',
            new_name='ac_2_employer_percentage',
        ),
    ]
