# Generated by Django 4.1.5 on 2023-08-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_rename_ac10_eps_employer_limit_pfesisetup_ac_10_eps_employer_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot_calculation', models.CharField(choices=[('26', '26'), ('30', '30'), ('month_days', 'month_days')], default='26', max_length=10)),
                ('el_calculation', models.CharField(choices=[('26', '26'), ('30', '30')], default='26', max_length=2)),
                ('notice_pay', models.CharField(choices=[('26', '26'), ('30', '30')], default='26', max_length=2)),
                ('service_calculation', models.CharField(choices=[('26', '26'), ('30', '30')], default='26', max_length=2)),
                ('gratuity_calculation', models.CharField(choices=[('26', '26'), ('30', '30')], default='26', max_length=2)),
                ('el_days_calculation', models.PositiveSmallIntegerField(default=20)),
            ],
        ),
    ]
