# Generated by Django 4.1.5 on 2023-08-04 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_remove_calculations_id_calculations_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculations',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='calculations', serialize=False, to='api.company'),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL),
        ),
    ]
