# Generated by Django 4.1.5 on 2023-08-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_calculations_company_alter_calculations_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculations',
            name='notice_pay',
            field=models.CharField(choices=[('26', '26'), ('30', '30')], default='30', max_length=2),
        ),
        migrations.AlterField(
            model_name='calculations',
            name='service_calculation',
            field=models.CharField(choices=[('26', '26'), ('30', '30')], default='30', max_length=2),
        ),
    ]
