# Generated by Django 4.1.5 on 2023-08-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_employeeshifts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofessionaldetail',
            name='shift',
        ),
    ]
