# Generated by Django 4.1.5 on 2023-08-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_remove_employeeprofessionaldetail_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavegrade',
            name='half_generate_frequency',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leavegrade',
            name='paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leavegrade',
            name='limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
