# Generated by Django 4.1.5 on 2023-08-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_leavegrade_half_generate_frequency_leavegrade_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavegrade',
            old_name='half_generate_frequency',
            new_name='generate_frequency',
        ),
    ]
