# Generated by Django 4.1.5 on 2023-08-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_employeeattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='late_hrs_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='ot_hrs_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
