# Generated by Django 4.1.5 on 2023-08-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_employeeattendance_late_hrs_min_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeattendance',
            old_name='late_hrs_min',
            new_name='late_min',
        ),
        migrations.RenameField(
            model_name='employeeattendance',
            old_name='ot_hrs_min',
            new_name='ot_min',
        ),
    ]
