# Generated by Django 4.1.5 on 2023-09-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_employeeattendance_manual_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='resignation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofessionaldetail',
            name='resigned',
            field=models.BooleanField(default=False),
        ),
    ]
