# Generated by Django 4.1.5 on 2023-09-06 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_employeeprofessionaldetail_resignation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGenerativeLeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('present_count', models.PositiveSmallIntegerField(default=0)),
                ('leave_count', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_employees_generative_leave_record', to='api.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generative_leave_record', to='api.employeepersonaldetail')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_generative_leave_record', to='api.leavegrade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_company_employees_generative_leave_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
