# Generated by Django 4.1.5 on 2023-09-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_employeegenerativeleaverecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeegenerativeleaverecord',
            old_name='month',
            new_name='date',
        ),
    ]
