# Generated by Django 4.1.5 on 2023-09-08 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_rename_month_employeegenerativeleaverecord_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_count', models.PositiveSmallIntegerField(default=0)),
                ('year', models.PositiveSmallIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_employees_leave_openings', to='api.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_opening', to='api.employeepersonaldetail')),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_leave_openings', to='api.leavegrade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_company_employees_leave_openings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
