# Generated by Django 4.1.5 on 2023-09-08 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_employeeleaveopening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleaveopening',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900, message='Year cannot be less than 1900.'), django.core.validators.MaxValueValidator(2100, message='Year cannot be more than 2100.')]),
        ),
        migrations.AddConstraint(
            model_name='employeeleaveopening',
            constraint=models.UniqueConstraint(fields=('employee', 'year', 'company'), name='unique_year_per_employee_per_company'),
        ),
    ]
