# Generated by Django 4.1.5 on 2023-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_alter_employeeleaveopening_year_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeegenerativeleaverecord',
            constraint=models.UniqueConstraint(fields=('employee', 'date', 'company', 'leave'), name='unique_date_per_employee_per_company'),
        ),
    ]
