# Generated by Django 4.1.5 on 2023-09-12 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_remove_employeegenerativeleaverecord_present_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.PositiveIntegerField()),
                ('emi', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('closed', models.BooleanField(default=False)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('tenure_months', models.PositiveSmallIntegerField()),
                ('repaid', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_employees_advance_payments', to='api.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='api.employeepersonaldetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_company_employees_advance_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
