# Generated by Django 4.1.5 on 2023-09-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_employeeadvancepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeadvancepayment',
            old_name='repaid',
            new_name='repaid_amount',
        ),
    ]
