# Generated by Django 4.1.5 on 2023-09-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_rename_tenure_months_employeeadvancepayment_tenure_months_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepfesidetail',
            name='vpf_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
