# Generated by Django 4.1.5 on 2023-09-15 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_employeepfesidetail_vpf_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMonthlyAttendanceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_count', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateField()),
                ('weekly_off_days', models.PositiveSmallIntegerField(default=0)),
                ('paid_days', models.PositiveSmallIntegerField(default=0)),
                ('holiday_days', models.PositiveSmallIntegerField(default=0)),
                ('not_paid_days', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_employees_present_count', to='api.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_count', to='api.employeepersonaldetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_company_employees_present_count', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeePresentCount',
        ),
    ]
