# Generated by Django 4.1.5 on 2023-09-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_employeemonthlyattendancedetails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemonthlyattendancedetails',
            old_name='holiday_days',
            new_name='holiday_days_count',
        ),
        migrations.RenameField(
            model_name='employeemonthlyattendancedetails',
            old_name='not_paid_days',
            new_name='not_paid_days_count',
        ),
        migrations.RenameField(
            model_name='employeemonthlyattendancedetails',
            old_name='paid_days',
            new_name='paid_days_count',
        ),
        migrations.RenameField(
            model_name='employeemonthlyattendancedetails',
            old_name='weekly_off_days',
            new_name='weekly_off_days_count',
        ),
    ]
