# Generated by Django 4.1.5 on 2023-09-18 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_rename_holiday_days_employeemonthlyattendancedetails_holiday_days_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemonthlyattendancedetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_company_employees_monthly_attendance_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployeeSalaryPrepared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('incentive_amount', models.PositiveIntegerField(default=0)),
                ('esi_deducted', models.PositiveIntegerField(default=0)),
                ('vpf_deducted', models.PositiveIntegerField(default=0)),
                ('advance_deducted', models.PositiveIntegerField(default=0)),
                ('tds_deducted', models.PositiveIntegerField(default=0)),
                ('others_deducted', models.PositiveIntegerField(default=0)),
                ('paid_days_count', models.PositiveSmallIntegerField(default=0)),
                ('present_count', models.PositiveSmallIntegerField(default=0)),
                ('weekly_off_days_count', models.PositiveSmallIntegerField(default=0)),
                ('holiday_days_count', models.PositiveSmallIntegerField(default=0)),
                ('not_paid_days_count', models.PositiveSmallIntegerField(default=0)),
                ('total_ot_minutes_monthly', models.PositiveSmallIntegerField(default=0)),
                ('total_ot_amount_monthly', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_employees_salaries_prepared', to='api.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries_prepared', to='api.employeepersonaldetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_company_employees_salaries_prepared', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
