# Generated by Django 4.1.5 on 2023-09-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_employeemonthlyattendancedetails_net_ot_minutes_monthly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalaryprepared',
            old_name='total_ot_amount_monthly',
            new_name='net_ot_amount_monthly',
        ),
        migrations.RenameField(
            model_name='employeesalaryprepared',
            old_name='total_ot_minutes_monthly',
            new_name='net_ot_minutes_monthly',
        ),
    ]
