# Generated by Django 4.1.5 on 2023-09-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_rename_total_ot_amount_monthly_employeesalaryprepared_net_ot_amount_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryprepared',
            name='pf_deducted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
