# Generated by Django 4.1.5 on 2023-09-19 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_employeesalaryprepared_pf_deducted'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(default=0)),
                ('earned_amount', models.PositiveIntegerField(default=0)),
                ('arear_amount', models.PositiveIntegerField(default=0)),
                ('earning_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earning_head_earned_amount', to='api.earningshead')),
                ('salary_prepared', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_salary_earned_amounts', to='api.employeesalaryprepared')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_company_employees_earned_amounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
