# Generated by Django 4.1.5 on 2023-09-24 13:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_earnedamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryprepared',
            name='labour_welfare_fund_deducted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeesalaryprepared',
            name='payment_mode',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('rtgs', 'RTGS'), ('neft', 'NEFT')], default='bank_transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='pfesisetup',
            name='enable_labour_welfare_fund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pfesisetup',
            name='labour_welfare_fund_limit',
            field=models.PositiveIntegerField(default=31),
        ),
        migrations.AddField(
            model_name='pfesisetup',
            name='labour_welfare_fund_percentage',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='pfesisetup',
            name='labour_wellfare_fund_employer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='employeesalaryprepared',
            constraint=models.UniqueConstraint(fields=('date', 'employee'), name='unique_salary_for_each_month'),
        ),
    ]
