# Generated by Django 4.1.5 on 2023-09-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_employeesalaryprepared_labour_welfare_fund_deducted_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='earnedamount',
            constraint=models.UniqueConstraint(fields=('earning_head', 'salary_prepared'), name='unique_earned_amount_for_each_earning_head'),
        ),
    ]
