# Generated by Django 4.1.5 on 2023-09-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_earnedamount_unique_earned_amount_for_each_earning_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalaryprepared',
            name='payment_mode',
        ),
    ]
