# Generated by Django 4.1.5 on 2023-09-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_remove_employeesalaryprepared_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryprepared',
            name='payment_mode',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('rtgs', 'RTGS'), ('neft', 'NEFT')], default='bank_transfer', max_length=20),
        ),
    ]
