# Generated by Django 4.1.5 on 2023-09-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_employeesalaryprepared_payment_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeesalaryprepared',
            name='unique_salary_for_each_month',
        ),
    ]
