# Generated by Django 4.1.5 on 2023-09-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_remove_employeesalaryprepared_unique_salary_for_each_month'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employeesalaryprepared',
            constraint=models.UniqueConstraint(fields=('date', 'employee'), name='unique_salary_for_each_month'),
        ),
    ]
