# Generated by Django 4.1.5 on 2023-09-29 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_employeesalaryprepared_unique_salary_for_each_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earnedamount',
            old_name='earning_head',
            new_name='earnings_head',
        ),
    ]
