# Generated by Django 4.1.5 on 2023-10-06 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_remove_earnedamount_unique_earned_amount_for_each_earning_head_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAdvanceEmiRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('employee_advance_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_emis_of_advance', to='api.company')),
                ('salary_prepared', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emis_with_salary_prepared', to='api.employeesalaryprepared')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_company_employees_advance_emi_repayments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
