# Generated by Django 4.1.5 on 2023-10-06 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_employeeadvanceemirepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeadvanceemirepayment',
            name='employee_advance_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_emis_of_advance', to='api.employeeadvancepayment'),
        ),
    ]
