# Generated by Django 4.1.5 on 2023-10-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_alter_employeeadvanceemirepayment_employee_advance_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeadvancepayment',
            name='repaid_amount',
        ),
    ]
