# Generated by Django 4.1.5 on 2023-10-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_remove_employeeadvancepayment_repaid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepfesidetail',
            name='tds_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
