# Generated by Django 4.1.5 on 2023-10-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_employeepfesidetail_tds_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyEmployeeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earliest_employee_date_of_joining', models.DateField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_statistics', to='api.company')),
            ],
        ),
    ]
