# Generated by Django 4.1.5 on 2023-10-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_companyemployeestatistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyEmployeeStatistics',
        ),
    ]
