# Generated by Django 4.1.5 on 2023-10-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_companyemployeestatistics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyEmployeeStatistics',
        ),
    ]
