# Generated by Django 4.1.5 on 2023-10-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_delete_companyemployeestatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='esi_no',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='head_office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='pf_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='phone_no',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
