# Generated by Django 4.1.5 on 2023-10-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_alter_companydetails_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemonthlyattendancedetails',
            name='compensation_off_days_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
