# Generated by Django 4.1.5 on 2023-11-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_employeemonthlyattendancedetails_compensation_off_days_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeepersonaldetail',
            name='father_or_husband_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetail',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetail',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetail',
            name='paycode',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetail',
            name='wife_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
