# Generated by Django 4.1.5 on 2023-11-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_alter_employeepersonaldetail_father_or_husband_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='involving_industry',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='key_person',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
